apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: block-devices-webhook
  name: block-devices-webhook
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: block-devices-webhook
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deploymentconfig: block-devices-webhook
    spec:
      containers:
      - image: ''
        imagePullPolicy: Always
        name: block-devices-webhook
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: webhook-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: webhook-cert
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - block-devices-webhook
      from:
        kind: ImageStreamTag
        name: block-devices-webhook:latest
        namespace: block-devices-webhook
    type: ImageChange
