apiVersion: v1
kind: Service
metadata:
  name: block-devices-webhook
  namespace: block-devices-webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 10250
  selector:
    deploymentconfig: block-devices-webhook
  sessionAffinity: None
  type: ClusterIP
